default:
    image: hub.ilearned.eu/i-learned/ci-cd/blog-builder
    tags:
        - AMD64

stages:
    - prod-deploy

prod-deploy-job:
    stage: prod-deploy
    script:
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" *.zone deploy@vm01.eban.eu.org:/var/lib/knot
        - ssh -i ~/.ssh/id_ed25519 deploy@vm01.eban.eu.org sudo -h 127.0.0.1 /bin/systemctl restart knot
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
