name: Copy zone

on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Requirement
        run: |
          sudo apt-get update
          sudo apt-get install -y bind9utils
          export EPOCH_TIME=$(date +%s)
          sed -i s/DYNAMIC_SOA/$EPOCH_TIME/ il.net.eu.org.zone
          sed -i s/DYNAMIC_SOA/$EPOCH_TIME/ ilearned.eu.org.zone
          sed -i s/DYNAMIC_SOA/$EPOCH_TIME/ ilearned.eu.zone

      - name: Lint
        run: |
          named-checkzone ilearned.eu ilearned.eu.zone
          named-checkzone ilearned.eu.org ilearned.eu.org.zone
          named-checkzone il.net.eu.org il.net.eu.org.zone
  deploy-ilearned-eu:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy zone
        run: |
          mkdir ${HOME}/.ssh
          echo "${{secrets.DEPLOY_KEY}}" > ${HOME}/.ssh/id_ed25519
          chmod 600 ${HOME}/.ssh/id_ed25519
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ${HOME}/.ssh/config
          eval $(ssh-agent -s)
          export EPOCH_TIME=$(date +%s)
          if [[ $(git diff HEAD~1 HEAD -- il.net.eu.org | wc -l) > 0 ]]; then
            sed -i s/DYNAMIC_SOA/$EPOCH_TIME/ il.net.eu.org.zone
            scp -i ${HOME}/.ssh/id_ed25519 il.net.eu.org.zone deploy@vm01.eban.eu.org:/var/lib/knot/
          fi
          if [[ $(git diff HEAD~1 HEAD -- ilearned.eu.org | wc -l) > 0 ]]; then
            sed -i s/DYNAMIC_SOA/$EPOCH_TIME/ ilearned.eu.org.zone
            scp -i ${HOME}/.ssh/id_ed25519 ilearned.eu.org.zone deploy@vm01.eban.eu.org:/var/lib/knot
          fi
          if [[ $(git diff HEAD~1 HEAD -- ilearned.eu | wc -l) > 0 ]]; then
            sed -i s/DYNAMIC_SOA/$EPOCH_TIME/ ilearned.eu.zone
            scp -i ${HOME}/.ssh/id_ed25519 ilearned.eu.zone deploy@vm01.eban.eu.org:/var/lib/knot
          fi
          ssh -i ${HOME}/.ssh/id_ed25519 deploy@vm01.eban.eu.org sudo /bin/systemctl restart knot
